id: I34BCF444
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T07:30:10+00:00'
last_modified: '2022-06-08T07:01:46.173065+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W2CZ7955
  title: མགོན་པོའི་རྒྱུད་སྐོར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    3CC5:
      image_group_id: I1KG3558
      title: ''
      total_pages: 648
      order: 1
      base_file: 3CC5.txt
    '3227':
      image_group_id: I1KG3559
      title: ''
      total_pages: 948
      order: 2
      base_file: 3227.txt
    36A6:
      image_group_id: I1KG3560
      title: ''
      total_pages: 434
      order: 3
      base_file: 36A6.txt
    84C5:
      image_group_id: I1KG3561
      title: ''
      total_pages: 483
      order: 4
      base_file: 84C5.txt
    9BF7:
      image_group_id: I1KG3562
      title: ''
      total_pages: 725
      order: 5
      base_file: 9BF7.txt
    EEDA:
      image_group_id: I1KG3563
      title: ''
      total_pages: 3
      order: 6
      base_file: EEDA.txt
    '4882':
      image_group_id: I1KG3564
      title: ''
      total_pages: 399
      order: 7
      base_file: 4882.txt
    CCC1:
      image_group_id: I1KG3565
      title: ''
      total_pages: 359
      order: 8
      base_file: CCC1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
