id: I34BCF444
legacy_id: P006812
ocr_import_info:
  bdrc_scan_id: W2CZ7955
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T07:29:14'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-09-02T15:31:45.640454+00:00'
last_modified: 2022-09-02 23:35:59.966853
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W2CZ7955
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  geo_restriction:
  - CN
  reproduction_of: http://purl.bdrc.io/resource/MW2CZ7955
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: མགོན་པོའི་རྒྱུད་སྐོར།
statistics:
  ocr_word_mean_confidence_index: 0.6450296004852297
  ocr_word_median_confidence_index: 0.6499999761581421
quality: null
bases:
  I1KG3565:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3565
      total_pages: 359
      volume_number: 8
      volume_pages_bdrc_intro: 2
    order: 8
    base_file: I1KG3565.txt
    statistics:
      ocr_word_median_confidence_index: 0.49000000953674316
      ocr_word_mean_confidence_index: 0.5638131741481404
    legacy_id: v008
  I1KG3564:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3564
      total_pages: 399
      volume_number: 7
      volume_pages_bdrc_intro: 2
    order: 7
    base_file: I1KG3564.txt
    statistics:
      ocr_word_median_confidence_index: 0.5
      ocr_word_mean_confidence_index: 0.5642699248070814
    legacy_id: v007
  I1KG3562:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3562
      total_pages: 725
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I1KG3562.txt
    statistics:
      ocr_word_median_confidence_index: 0.5799999833106995
      ocr_word_mean_confidence_index: 0.6153950922485364
    legacy_id: v005
  I1KG3559:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3559
      total_pages: 948
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG3559.txt
    statistics:
      ocr_word_median_confidence_index: 0.5299999713897705
      ocr_word_mean_confidence_index: 0.5755059744323409
    legacy_id: v002
  I1KG3563:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3563
      total_pages: 3
      volume_number: 6
      volume_pages_bdrc_intro: 2
    order: 6
    base_file: I1KG3563.txt
    statistics:
      ocr_word_median_confidence_index: 0.9900000095367432
      ocr_word_mean_confidence_index: 0.9605000073711077
    legacy_id: v006
  I1KG3561:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3561
      total_pages: 483
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I1KG3561.txt
    statistics:
      ocr_word_median_confidence_index: 0.5400000214576721
      ocr_word_mean_confidence_index: 0.5931041487894478
    legacy_id: v004
  I1KG3558:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3558
      total_pages: 648
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG3558.txt
    statistics:
      ocr_word_median_confidence_index: 0.8299999833106995
      ocr_word_mean_confidence_index: 0.7517881799349558
    legacy_id: v001
  I1KG3560:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG3560
      total_pages: 434
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I1KG3560.txt
    statistics:
      ocr_word_median_confidence_index: 0.550000011920929
      ocr_word_mean_confidence_index: 0.5974231314959664
    legacy_id: v003
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
